### ISSUE TITLE
File not found error when trying to insert gif

### ISSUE THREAD

**Issue by localhankio** [johnstew/vscode-gif#2]
I open the pallet and try to enter a gif but I get
`\\C:\Users\UserNameHere\.vscode\extensions\johnstew.gif-0.0.1\out\src\gif\3d20393c-gif-preview-agree.html`

I think the first two backslashes are added and that's messing up the file retrieval. When I go into file explorer and remove them so it just
`C:\Users\Henry Shen\.vscode\extensions\johnstew.gif-0.0.1\out\src\gif\3d20393c-gif-preview-agree.html`
then the gifs page opens up in the browser. Looked at the source code and couldn't find anywhere that two backslashes were added. Problem with Windows compatibility?

**Comment by johnstew** [comment]
@shenryHen looks like this could be an issue with this [line](https://github.com/johnstew/vscode-gif/blob/master/src/main.ts#L14). 

I'm not sure if there I need to do a specific Windows check and if so then just open the file without the `file://` or maybe I don't need that at all. Let me do some testing and see what I can dig up.

Thanks!

**Comment by johnstew** [comment]
Its looking like I didn't need the `file://` and also needed to switch and use `Uri.file` instead. 

**Sources**
- https://github.com/Microsoft/vscode-uri/blob/master/lib/index.ts#L129
- https://github.com/Microsoft/vscode-uri/blob/master/lib/index.ts#L212

Need to verify on Windows.

**Comment by Jsydog222** [comment]
![Screenshot_20240829-174242](https://github.com/user-attachments/assets/627695e6-666b-4467-a60e-b3e974170026)
